### ISSUE TITLE
No apps being detected, fallback not used either

### ISSUE THREAD

**Issue by bananacity** [dlprows/FocusVolumeControl#1]
Firstly thanks for making this plugin, it's the one thing I wished elgato added to the volume controller plugin.

Unfortunately, I installed it on my stream deck + and it hasn't displayed any apps so far to let me control. I'm using version 6.3.0.18947 of  the stream deck software on windows. using the volume controller plugin lets me control all apps like normal.

I set the fallback to main system volume but it isn't falling back to this either and just flashed red when i touch the screen or dial.

Not sure if anyone else had this happen maybe you know what to try out

**Comment by Munchiesz** [comment]
Having the same issue. It doesnt work for 90% of application. 
Seems to be working for Davinci Resolve, but nothing else that i use

**Comment by dlprows** [comment]
I've unfortunately not come up with a perfect way of matching the focused window to an audio session from the volume mixer

If you have a specific application that it can't detect, then i can install it and update the algorithm to try to be more reliable at detecting the apps

Also, just to note, if it doesn't show up in the windows volume mixer, then it will use the fallback. For example, if you open notepad, it doesn't have a volume control, so it will use the fallback.


if its not falling back to the system volume, and its flashing red when turning the dial or touching the screen, then the application crashed. I have a fix for it, I've just been working on testing it out before sending it to elgato to update the marketplace
